In [2]:
import numpy as np
import random


In [3]:
A = np.array([[1,2,3],[2,1,4]])
print(A)

[[1 2 3]
 [2 1 4]]


In [4]:
#QUESTION 1

A = np.array([[1,2,3],[2,1,4]])
B = np.array([[1,0],[2,1],[3,2]])
C = np.array([[3,-1,3],[4,1,5],[2,1,3]])
D = np.array([[2,-4,5],[0,1,4],[3,2,1]])
E = np.array([[3,-2],[2,4]])

#1
2*(A.transpose())



array([[2, 4],
       [4, 2],
       [6, 8]])

In [5]:
#2
#(A-B).transpose()
#not possible

In [6]:
#3
((3*(B.transpose())-A)).transpose()

array([[ 2, -2],
       [ 4,  2],
       [ 6,  2]])

In [7]:
#4
#(((-1)*A).transpose())*E
#not possible

In [8]:
#5
#(np.add(C,2*(D.transpose())E)).transpose()
#not possible

In [9]:
#QUESTON 2

A = np.array([[1,4],[3,2]])
B = np.array([[2,-1],[-3,4]])

product_1 = A*B
print(product_1)
product_2 = B*A
print(product_2)

if(product_1.all() == product_2.all()):
    print("AB = BA \n Hence proved!")
else:
    print("AB != BA\n Hence proved!")

[[ 2 -4]
 [-9  8]]
[[ 2 -4]
 [-9  8]]
AB = BA 
 Hence proved!


In [10]:
#QUESTION 3

v1 = np.array([1,0,-1])
v2 = np.array([1,np.sqrt(2),1])
v3 = np.array([1,-(np.sqrt(2)),1])

In [11]:
r1 = int(np.dot(v1,v2))
r2 = int(np.dot(v2,v3))
r3 = int(np.dot(v1,v3))

if(r1==r2==r3==0):
    print("Orthogonal vectors!")
else:
    print("given vectors are not orthogonal!")



Orthogonal vectors!


In [12]:
n1 = np.linalg.norm(v1)
n2 = np.linalg.norm(v2)
n3 = np.linalg.norm(v3)

v1_ = v1/n1
v2_ = v2/n2
v3_ = v3/n3

print(v1_,",",v2_,",",v3_)

[ 0.70710678  0.         -0.70710678] , [0.5        0.70710678 0.5       ] , [ 0.5        -0.70710678  0.5       ]


In [13]:
#QUESTION 4

n = random.randint(0,100)
m = random.randint(0,100)
x = np.random.randint(n,size=(m,1))
y = np.random.randint(m,size=(n,1))

rank = np.linalg.matrix_rank(x*y.T)
print("rank = ",rank)

rank =  1


In [18]:
#QUESTION 5

#theoretically proved
               


In [15]:
#QUESTION 6

n = random.randint(0,100)
x = np.random.randint(n,size=(n,n))


if( (x*(x.T)).all() == ((x*(x.T)).T).all()):
    print("xxT is symmetrical")
else:
    print("xxT is not symmetrical")



v = np.random.random((n, 1))

if(np.dot(v.T, (x.T)*x*v).all() >= 0):
    is_positive_semi_definite = True
else:
    is_positive_semi_definite = False

is_positive_definite = np.linalg.matrix_rank(X) == min(m, n)


print("Positive Semi-Definite:", is_positive_semi_definite)
print("Positive Definite (if rank full):", is_positive_definite)



xxT is symmetrical
Positive Semi-Definite: True
Positive Definite (if rank full): True


In [17]:
#QUESTION 7 

def g(x, y):
    return np.exp(x) + np.exp(y) + np.exp(-2*x*y) - np.log(x**2*y)

def partial_derivative_x(func, x, y, h=1e-6):
    return (func(x + h, y) - func(x, y)) / h

def partial_derivative_y(func, x, y, h=1e-6):
    return (func(x, y + h) - func(x, y)) / h

x_val = 1.0
y_val = 1.0

dg_dx = partial_derivative_x(g, x_val, y_val)
dg_dy = partial_derivative_y(g, x_val, y_val)

print("Partial derivative of g with respect to x (dg/dx):", dg_dx)
print("Partial derivative of g with respect to y (dg/dy):", dg_dy)


Partial derivative of g with respect to x (dg/dx): 0.44761389172975896
Partial derivative of g with respect to y (dg/dy): 1.4476133918250866


In [53]:
#QUESTION 8
A = np.array([[2, 1, 3], [1, 1, 2], [3, 2, 5]])

eigenvalues, eigenvectors = np.linalg.eig(A)


print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for i in range(len(eigenvalues)):
    print(f"Eigenvalue {i + 1}: {eigenvalues[i]}, Eigenvector: {eigenvectors[:, i]}")



Eigenvalues: [7.60555128e+00 3.94448725e-01 2.68593972e-16]
Eigenvectors:
Eigenvalue 1: 7.6055512754639905, Eigenvector: [-0.49079864 -0.31970025 -0.81049889]
Eigenvalue 2: 0.39444872453601054, Eigenvector: [-0.65252078  0.75130448  0.0987837 ]
Eigenvalue 3: 2.685939715055778e-16, Eigenvector: [-0.57735027 -0.57735027  0.57735027]


In [54]:
# Eigen-decomposition
P = eigenvectors
D = np.diag(eigenvalues)
A_decomposition = P * D * np.linalg.inv(P)

print("Eigen-decomposition of A:")
print(A_decomposition)

Eigen-decomposition of A:
[[ 1.83205029e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.22649902e-01 -0.00000000e+00]
 [ 0.00000000e+00 -0.00000000e+00  8.95313238e-17]]


In [55]:
# Rank of A
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)


Rank of A: 2


In [56]:
# Check positive definiteness
is_positive_definite = np.all(np.linalg.eigvals(A) > 0)
print("Is A positive definite:", is_positive_definite)


Is A positive definite: True


In [57]:
# Check positive semi-definiteness
is_positive_semi_definite = np.all(np.linalg.eigvals(A) >= 0)
print("Is A positive semi-definite:", is_positive_semi_definite)


Is A positive semi-definite: True


In [58]:
# Check singularity
is_singular = np.linalg.det(A) == 0
print("Is A singular:", is_singular)

Is A singular: False
